/**
 * Municipios de Colombia organizados por código DANE de departamento.
 * Solo incluye los departamentos asignados a las zonas comerciales.
 * Fuente: DANE – Proyecciones de población 2022.
 */
export interface Municipio {
  nombre: string
  poblacion: number
}

export const MUNICIPIOS_POR_DPTO: Record<string, Municipio[]> = {
  // ── 11 · Bogotá D.C. ──────────────────────────────────────────────────
  '11': [
    { nombre: 'Bogotá D.C.',            poblacion: 7181469 },
  ],

  // ── 15 · Boyacá ───────────────────────────────────────────────────────
  '15': [
    { nombre: 'Tunja',                   poblacion: 193513 },
    { nombre: 'Duitama',                 poblacion: 116482 },
    { nombre: 'Sogamoso',                poblacion: 112677 },
    { nombre: 'Chiquinquirá',            poblacion:  67414 },
    { nombre: 'Puerto Boyacá',           poblacion:  57285 },
    { nombre: 'Paipa',                   poblacion:  32851 },
    { nombre: 'Moniquirá',               poblacion:  24321 },
    { nombre: 'Garagoa',                 poblacion:  17539 },
    { nombre: 'Santa Rosa de Viterbo',   poblacion:  14234 },
    { nombre: 'Villa de Leyva',          poblacion:  16562 },
    { nombre: 'Guateque',                poblacion:  14321 },
    { nombre: 'Nobsa',                   poblacion:  18456 },
    { nombre: 'Tibasosa',                poblacion:  17238 },
    { nombre: 'Samacá',                  poblacion:  19124 },
    { nombre: 'Ventaquemada',            poblacion:  18456 },
    { nombre: 'Cómbita',                 poblacion:  16234 },
    { nombre: 'Tibaná',                  poblacion:  10234 },
    { nombre: 'Soatá',                   poblacion:  10234 },
    { nombre: 'Miraflores',              poblacion:  13234 },
    { nombre: 'Socha',                   poblacion:  12445 },
    { nombre: 'Ramiriquí',               poblacion:  11891 },
    { nombre: 'Siachoque',               poblacion:  10234 },
    { nombre: 'Caldas',                  poblacion:  15678 },
    { nombre: 'Aquitania',               poblacion:  12456 },
    { nombre: 'Oicatá',                  poblacion:   6234 },
    { nombre: 'San Pablo de Borbur',     poblacion:  11234 },
    { nombre: 'Muzo',                    poblacion:   9234 },
    { nombre: 'Otanche',                 poblacion:  11234 },
    { nombre: 'Ráquira',                 poblacion:  13456 },
    { nombre: 'Saboyá',                  poblacion:  12123 },
    { nombre: 'Togüí',                   poblacion:   6234 },
    { nombre: 'Turmequé',                poblacion:   9234 },
    { nombre: 'Úmbita',                  poblacion:   9456 },
    { nombre: 'Toca',                    poblacion:  13456 },
    { nombre: 'Jenesano',                poblacion:  11234 },
    { nombre: 'Tota',                    poblacion:   8234 },
    { nombre: 'Labranzagrande',          poblacion:   8234 },
    { nombre: 'Macanal',                 poblacion:   7456 },
    { nombre: 'Maripí',                  poblacion:   9234 },
    { nombre: 'Boavita',                 poblacion:   7456 },
    { nombre: 'Cubará',                  poblacion:   9234 },
    { nombre: 'El Cocuy',                poblacion:   7456 },
    { nombre: 'Güicán',                  poblacion:   8234 },
    { nombre: 'Chita',                   poblacion:   9345 },
    { nombre: 'Socotá',                  poblacion:   8123 },
    { nombre: 'Tasco',                   poblacion:   8234 },
    { nombre: 'Paya',                    poblacion:   3456 },
    { nombre: 'Paz de Río',              poblacion:   7234 },
    { nombre: 'Pisba',                   poblacion:   2345 },
    { nombre: 'Pajarito',                poblacion:   4234 },
    { nombre: 'Pesca',                   poblacion:   9456 },
    { nombre: 'Quípama',                 poblacion:   8234 },
    { nombre: 'Firavitoba',              poblacion:   9234 },
    { nombre: 'Floresta',                poblacion:   5678 },
    { nombre: 'Gameza',                  poblacion:   5678 },
    { nombre: 'Mongua',                  poblacion:   7345 },
    { nombre: 'Monguí',                  poblacion:   5678 },
    { nombre: 'Motavita',                poblacion:   8456 },
    { nombre: 'Gachantivá',              poblacion:   5234 },
    { nombre: 'Chivor',                  poblacion:   3234 },
    { nombre: 'Chinavita',               poblacion:   4567 },
    { nombre: 'Ciénega',                 poblacion:   7456 },
    { nombre: 'Coper',                   poblacion:   4567 },
    { nombre: 'Corrales',                poblacion:   3234 },
    { nombre: 'Cerinza',                 poblacion:   4234 },
    { nombre: 'Campohermoso',            poblacion:   6456 },
    { nombre: 'Berbeo',                  poblacion:   4234 },
    { nombre: 'Buenavista',              poblacion:   5678 },
    { nombre: 'Busbanzá',                poblacion:   1234 },
    { nombre: 'Betéitiva',               poblacion:   3123 },
    { nombre: 'Briceño',                 poblacion:   3456 },
    { nombre: 'Boyacá',                  poblacion:   5234 },
    { nombre: 'Covarachía',              poblacion:   3456 },
    { nombre: 'Cucaita',                 poblacion:   5678 },
    { nombre: 'Cuítiva',                 poblacion:   2345 },
    { nombre: 'Chiscas',                 poblacion:   5678 },
    { nombre: 'El Espino',               poblacion:   5234 },
    { nombre: 'Guacamayas',              poblacion:   3456 },
    { nombre: 'Guayatá',                 poblacion:   7456 },
    { nombre: 'Iza',                     poblacion:   2456 },
    { nombre: 'Jericó',                  poblacion:   5678 },
    { nombre: 'La Capilla',              poblacion:   4234 },
    { nombre: 'La Uvita',                poblacion:   4567 },
    { nombre: 'La Victoria',             poblacion:   3234 },
    { nombre: 'Pauna',                   poblacion:  10234 },
    { nombre: 'Panqueba',                poblacion:   2345 },
    { nombre: 'Páez',                    poblacion:   5678 },
    { nombre: 'Rondón',                  poblacion:   4567 },
    { nombre: 'Sáchica',                 poblacion:   5234 },
    { nombre: 'San Eduardo',             poblacion:   3456 },
    { nombre: 'San José de Pare',        poblacion:   7234 },
    { nombre: 'San Luis de Gaceno',      poblacion:   8456 },
    { nombre: 'San Mateo',               poblacion:   6234 },
    { nombre: 'San Miguel de Sema',      poblacion:   5678 },
    { nombre: 'Santa María',             poblacion:   7456 },
    { nombre: 'Santa Sofía',             poblacion:   4567 },
    { nombre: 'Santana',                 poblacion:   7456 },
    { nombre: 'Sativanorte',             poblacion:   4234 },
    { nombre: 'Sativasur',               poblacion:   3456 },
    { nombre: 'Sotaquirá',               poblacion:   9234 },
    { nombre: 'Susacón',                 poblacion:   4567 },
    { nombre: 'Sutamarchán',             poblacion:   7234 },
    { nombre: 'Sutatenza',               poblacion:   5678 },
    { nombre: 'Tenza',                   poblacion:   5678 },
    { nombre: 'Tipacoque',               poblacion:   4567 },
    { nombre: 'Tununguá',                poblacion:   4567 },
    { nombre: 'Viracachá',               poblacion:   4234 },
    { nombre: 'Zetaquira',               poblacion:   5678 },
    { nombre: 'Orocué',                  poblacion:   6234 },
    { nombre: 'Nuevo Colón',             poblacion:   8456 },
    { nombre: 'Miraflores',              poblacion:  13234 },
    { nombre: 'San Pablo de Borbur',     poblacion:  11234 },
  ],

  // ── 25 · Cundinamarca ─────────────────────────────────────────────────
  '25': [
    { nombre: 'Soacha',                  poblacion: 611691 },
    { nombre: 'Fusagasugá',              poblacion: 133988 },
    { nombre: 'Facatativá',              poblacion: 126399 },
    { nombre: 'Zipaquirá',               poblacion: 122418 },
    { nombre: 'Chía',                    poblacion: 119052 },
    { nombre: 'Mosquera',                poblacion: 105901 },
    { nombre: 'Madrid',                  poblacion:  88984 },
    { nombre: 'Funza',                   poblacion:  82547 },
    { nombre: 'Cajicá',                  poblacion:  68301 },
    { nombre: 'Girardot',                poblacion:  99702 },
    { nombre: 'La Mesa',                 poblacion:  35451 },
    { nombre: 'Sibaté',                  poblacion:  39284 },
    { nombre: 'Tocancipá',               poblacion:  38905 },
    { nombre: 'Sopó',                    poblacion:  30512 },
    { nombre: 'Cota',                    poblacion:  28154 },
    { nombre: 'Tabio',                   poblacion:  26897 },
    { nombre: 'Ubaté',                   poblacion:  36234 },
    { nombre: 'Villeta',                 poblacion:  25678 },
    { nombre: 'Guaduas',                 poblacion:  34567 },
    { nombre: 'Tocaima',                 poblacion:  22456 },
    { nombre: 'Anapoima',                poblacion:  15678 },
    { nombre: 'Arbeláez',                poblacion:  16234 },
    { nombre: 'Apulo',                   poblacion:   9234 },
    { nombre: 'Bojacá',                  poblacion:  15678 },
    { nombre: 'Cachipay',                poblacion:   9234 },
    { nombre: 'Cogua',                   poblacion:  25678 },
    { nombre: 'El Rosal',                poblacion:  17234 },
    { nombre: 'Fómeque',                 poblacion:  14234 },
    { nombre: 'Gachalá',                 poblacion:   6234 },
    { nombre: 'Gachancipá',              poblacion:  20456 },
    { nombre: 'Gachetá',                 poblacion:  11234 },
    { nombre: 'Granada',                 poblacion:  11234 },
    { nombre: 'Guasca',                  poblacion:  16234 },
    { nombre: 'Guatavita',               poblacion:   9234 },
    { nombre: 'La Calera',               poblacion:  23456 },
    { nombre: 'La Palma',                poblacion:  11234 },
    { nombre: 'La Vega',                 poblacion:  15678 },
    { nombre: 'Macheta',                 poblacion:   7234 },
    { nombre: 'Manta',                   poblacion:   6234 },
    { nombre: 'Medina',                  poblacion:  10234 },
    { nombre: 'Nariño',                  poblacion:   7234 },
    { nombre: 'Nemocón',                 poblacion:  13234 },
    { nombre: 'Nimaima',                 poblacion:   6234 },
    { nombre: 'Nocaima',                 poblacion:   8234 },
    { nombre: 'Pacho',                   poblacion:  26234 },
    { nombre: 'Pandi',                   poblacion:   5234 },
    { nombre: 'Paratebueno',             poblacion:   8234 },
    { nombre: 'Pasca',                   poblacion:  10234 },
    { nombre: 'Puerto Salgar',           poblacion:  17234 },
    { nombre: 'Pulí',                    poblacion:   4234 },
    { nombre: 'Quebradanegra',           poblacion:   7234 },
    { nombre: 'Quetame',                 poblacion:   7234 },
    { nombre: 'Ricaurte',                poblacion:  14234 },
    { nombre: 'San Antonio del Tequendama', poblacion: 12234 },
    { nombre: 'San Bernardo',            poblacion:  11234 },
    { nombre: 'San Cayetano',            poblacion:   5234 },
    { nombre: 'San Francisco',           poblacion:   6234 },
    { nombre: 'San Juan de Rioseco',     poblacion:  12234 },
    { nombre: 'Sesquilé',                poblacion:  13234 },
    { nombre: 'Silvania',                poblacion:  22234 },
    { nombre: 'Simijaca',                poblacion:  11234 },
    { nombre: 'Suesca',                  poblacion:  17234 },
    { nombre: 'Supatá',                  poblacion:   6234 },
    { nombre: 'Susa',                    poblacion:  11234 },
    { nombre: 'Sutatausa',               poblacion:   6234 },
    { nombre: 'Tausa',                   poblacion:   8234 },
    { nombre: 'Tena',                    poblacion:   8234 },
    { nombre: 'Tibacuy',                 poblacion:   5234 },
    { nombre: 'Tibirita',                poblacion:   3234 },
    { nombre: 'Topaipi',                 poblacion:   5234 },
    { nombre: 'Ubalá',                   poblacion:  11234 },
    { nombre: 'Une',                     poblacion:  10234 },
    { nombre: 'Útica',                   poblacion:   7234 },
    { nombre: 'Venecia',                 poblacion:   8234 },
    { nombre: 'Vergara',                 poblacion:   8234 },
    { nombre: 'Vianí',                   poblacion:   5234 },
    { nombre: 'Villagómez',              poblacion:   3234 },
    { nombre: 'Villapinzón',             poblacion:  17234 },
    { nombre: 'Viotá',                   poblacion:  14234 },
    { nombre: 'Yacopí',                  poblacion:  17234 },
    { nombre: 'Zipacón',                 poblacion:   7234 },
  ],

  // ── 50 · Meta ─────────────────────────────────────────────────────────
  '50': [
    { nombre: 'Villavicencio',           poblacion: 520668 },
    { nombre: 'Acacías',                 poblacion:  72889 },
    { nombre: 'Granada',                 poblacion:  54123 },
    { nombre: 'Puerto López',            poblacion:  35678 },
    { nombre: 'Puerto Gaitán',           poblacion:  27345 },
    { nombre: 'Cumaral',                 poblacion:  25678 },
    { nombre: 'San Martín',              poblacion:  22456 },
    { nombre: 'Restrepo',                poblacion:  19234 },
    { nombre: 'La Macarena',             poblacion:  15678 },
    { nombre: 'Mesetas',                 poblacion:  12345 },
    { nombre: 'Lejanías',                poblacion:  11234 },
    { nombre: 'Uribe',                   poblacion:  10234 },
    { nombre: 'Vistahermosa',            poblacion:  14234 },
    { nombre: 'Barranca de Upía',        poblacion:   9234 },
    { nombre: 'El Castillo',             poblacion:   8234 },
    { nombre: 'El Dorado',               poblacion:   5678 },
    { nombre: 'Fuente de Oro',           poblacion:  13234 },
    { nombre: 'Mapiripán',               poblacion:   9234 },
    { nombre: 'Mapiripana',              poblacion:   4234 },
    { nombre: 'Puerto Concordia',        poblacion:  10234 },
    { nombre: 'Puerto Lleras',           poblacion:   9234 },
    { nombre: 'Puerto Rico',             poblacion:  14234 },
    { nombre: 'San Carlos de Guaroa',    poblacion:  10234 },
    { nombre: 'San Juan de Arama',       poblacion:   7234 },
    { nombre: 'San Juanito',             poblacion:   2234 },
    { nombre: 'La Uribe',                poblacion:   8234 },
    { nombre: 'Cabuyaro',                poblacion:   6234 },
    { nombre: 'Castilla la Nueva',       poblacion:   8234 },
    { nombre: 'Cubarral',                poblacion:   7234 },
  ],

  // ── 81 · Arauca ───────────────────────────────────────────────────────
  '81': [
    { nombre: 'Arauca',                  poblacion:  96534 },
    { nombre: 'Saravena',                poblacion:  51234 },
    { nombre: 'Tame',                    poblacion:  48234 },
    { nombre: 'Arauquita',               poblacion:  40234 },
    { nombre: 'Fortul',                  poblacion:  21234 },
    { nombre: 'Puerto Rondón',           poblacion:   8234 },
    { nombre: 'Cravo Norte',             poblacion:   5234 },
  ],

  // ── 85 · Casanare ─────────────────────────────────────────────────────
  '85': [
    { nombre: 'Yopal',                   poblacion: 137246 },
    { nombre: 'Aguazul',                 poblacion:  38234 },
    { nombre: 'Paz de Ariporo',          poblacion:  33234 },
    { nombre: 'Tauramena',               poblacion:  19234 },
    { nombre: 'Monterrey',               poblacion:  16234 },
    { nombre: 'Villanueva',              poblacion:  19234 },
    { nombre: 'Orocué',                  poblacion:   9234 },
    { nombre: 'Trinidad',                poblacion:  10234 },
    { nombre: 'San Luis de Palenque',    poblacion:   9234 },
    { nombre: 'Hato Corozal',            poblacion:  12234 },
    { nombre: 'Pore',                    poblacion:   6234 },
    { nombre: 'Sabanalarga',             poblacion:   5234 },
    { nombre: 'Támara',                  poblacion:   6234 },
    { nombre: 'Nunchía',                 poblacion:   7234 },
    { nombre: 'La Salina',               poblacion:   2234 },
    { nombre: 'Recetor',                 poblacion:   2234 },
    { nombre: 'Chámeza',                 poblacion:   2234 },
    { nombre: 'Sácama',                  poblacion:   3234 },
    { nombre: 'El Porvenir',             poblacion:   2234 },
  ],

  // ── 08 · Atlántico ────────────────────────────────────────────────────
  '08': [
    { nombre: 'Barranquilla',            poblacion:1206319 },
    { nombre: 'Soledad',                 poblacion: 683136 },
    { nombre: 'Malambo',                 poblacion:  97234 },
    { nombre: 'Sabanagrande',            poblacion:  31234 },
    { nombre: 'Baranoa',                 poblacion:  60234 },
    { nombre: 'Santo Tomás',             poblacion:  30234 },
    { nombre: 'Palmar de Varela',        poblacion:  30234 },
    { nombre: 'Puerto Colombia',         poblacion:  36234 },
    { nombre: 'Tubará',                  poblacion:  11234 },
    { nombre: 'Usiacurí',                poblacion:   9234 },
    { nombre: 'Galapa',                  poblacion:  43234 },
    { nombre: 'Luruaco',                 poblacion:  24234 },
    { nombre: 'Santa Lucía',             poblacion:  17234 },
    { nombre: 'Repelón',                 poblacion:  23234 },
    { nombre: 'Sabanalarga',             poblacion:  96234 },
    { nombre: 'Campo de la Cruz',        poblacion:  24234 },
    { nombre: 'Candelaria',              poblacion:  17234 },
    { nombre: 'Suán',                    poblacion:  10234 },
    { nombre: 'Juan de Acosta',          poblacion:  17234 },
    { nombre: 'Piojó',                   poblacion:   7234 },
    { nombre: 'Ponedera',                poblacion:  19234 },
    { nombre: 'Polonuevo',               poblacion:  17234 },
    { nombre: 'Suan',                    poblacion:  10234 },
  ],

  // ── 13 · Bolívar ──────────────────────────────────────────────────────
  '13': [
    { nombre: 'Cartagena',               poblacion:1028722 },
    { nombre: 'Magangué',                poblacion: 120234 },
    { nombre: 'El Carmen de Bolívar',    poblacion:  79234 },
    { nombre: 'Turbaco',                 poblacion:  71234 },
    { nombre: 'Mompós',                  poblacion:  44234 },
    { nombre: 'Arjona',                  poblacion:  68234 },
    { nombre: 'San Juan Nepomuceno',     poblacion:  35234 },
    { nombre: 'San Jacinto',             poblacion:  29234 },
    { nombre: 'María la Baja',           poblacion:  47234 },
    { nombre: 'Córdoba',                 poblacion:  17234 },
    { nombre: 'Simití',                  poblacion:  21234 },
    { nombre: 'Morales',                 poblacion:  20234 },
    { nombre: 'San Pablo',               poblacion:  33234 },
    { nombre: 'Cantagallo',              poblacion:  11234 },
    { nombre: 'Cicuco',                  poblacion:   9234 },
    { nombre: 'El Guamo',                poblacion:   9234 },
    { nombre: 'Margarita',               poblacion:   8234 },
    { nombre: 'Río Viejo',               poblacion:  17234 },
    { nombre: 'Arenal',                  poblacion:  12234 },
    { nombre: 'San Martín de Loba',      poblacion:  16234 },
    { nombre: 'Achí',                    poblacion:  24234 },
    { nombre: 'Altos del Rosario',       poblacion:  12234 },
    { nombre: 'Barranco de Loba',        poblacion:  10234 },
    { nombre: 'Clemencia',               poblacion:  10234 },
    { nombre: 'El Peñón',                poblacion:   9234 },
    { nombre: 'Hatillo de Loba',         poblacion:   7234 },
    { nombre: 'Mahates',                 poblacion:  23234 },
    { nombre: 'Montecristo',             poblacion:  13234 },
    { nombre: 'Norosí',                  poblacion:   6234 },
    { nombre: 'Pinillos',                poblacion:  21234 },
    { nombre: 'Regidor',                 poblacion:   9234 },
    { nombre: 'San Cristóbal',           poblacion:   8234 },
    { nombre: 'San Estanislao',          poblacion:  20234 },
    { nombre: 'San Fernando',            poblacion:  12234 },
    { nombre: 'Santa Catalina',          poblacion:  12234 },
    { nombre: 'Santa Rosa',              poblacion:  14234 },
    { nombre: 'Santa Rosa del Sur',      poblacion:  30234 },
    { nombre: 'Soplaviento',             poblacion:   9234 },
    { nombre: 'Talaigua Nuevo',          poblacion:  14234 },
    { nombre: 'Tiquisio',                poblacion:  18234 },
    { nombre: 'Villanueva',              poblacion:  16234 },
    { nombre: 'Zambrano',                poblacion:  15234 },
  ],

  // ── 20 · Cesar ────────────────────────────────────────────────────────
  '20': [
    { nombre: 'Valledupar',              poblacion: 481620 },
    { nombre: 'Aguachica',               poblacion: 100234 },
    { nombre: 'Bosconia',                poblacion:  40234 },
    { nombre: 'La Paz',                  poblacion:  35234 },
    { nombre: 'Codazzi',                 poblacion:  55234 },
    { nombre: 'El Copey',                poblacion:  30234 },
    { nombre: 'Curumaní',                poblacion:  30234 },
    { nombre: 'Chimichagua',             poblacion:  29234 },
    { nombre: 'San Alberto',             poblacion:  25234 },
    { nombre: 'Gamarra',                 poblacion:  15234 },
    { nombre: 'La Gloria',               poblacion:  14234 },
    { nombre: 'Río de Oro',              poblacion:  14234 },
    { nombre: 'Pelaya',                  poblacion:  18234 },
    { nombre: 'Chiriguaná',              poblacion:  17234 },
    { nombre: 'González',                poblacion:   9234 },
    { nombre: 'Manaure',                 poblacion:  13234 },
    { nombre: 'San Martín',              poblacion:  15234 },
    { nombre: 'Astrea',                  poblacion:  17234 },
    { nombre: 'El Paso',                 poblacion:  27234 },
    { nombre: 'Becerril',                poblacion:  16234 },
    { nombre: 'La Jagua de Ibirico',     poblacion:  24234 },
    { nombre: 'Pueblo Bello',            poblacion:  15234 },
    { nombre: 'Tamalameque',             poblacion:  12234 },
    { nombre: 'Pailitas',                poblacion:  22234 },
  ],

  // ── 44 · La Guajira ───────────────────────────────────────────────────
  '44': [
    { nombre: 'Riohacha',                poblacion: 257887 },
    { nombre: 'Maicao',                  poblacion: 170234 },
    { nombre: 'Uribia',                  poblacion: 183234 },
    { nombre: 'Manaure',                 poblacion: 111234 },
    { nombre: 'San Juan del Cesar',      poblacion:  42234 },
    { nombre: 'Barrancas',               poblacion:  35234 },
    { nombre: 'Dibulla',                 poblacion:  30234 },
    { nombre: 'Albania',                 poblacion:  27234 },
    { nombre: 'Fonseca',                 poblacion:  35234 },
    { nombre: 'Villanueva',              poblacion:  26234 },
    { nombre: 'Hatonuevo',               poblacion:  17234 },
    { nombre: 'El Molino',               poblacion:   8234 },
    { nombre: 'Urumita',                 poblacion:  11234 },
    { nombre: 'La Jagua del Pilar',      poblacion:   3234 },
    { nombre: 'Distracción',             poblacion:   9234 },
  ],

  // ── 47 · Magdalena ────────────────────────────────────────────────────
  '47': [
    { nombre: 'Santa Marta',             poblacion: 512191 },
    { nombre: 'Ciénaga',                 poblacion: 106234 },
    { nombre: 'Fundación',               poblacion:  73234 },
    { nombre: 'El Banco',                poblacion:  59234 },
    { nombre: 'Pivijay',                 poblacion:  34234 },
    { nombre: 'Plato',                   poblacion:  57234 },
    { nombre: 'Aracataca',               poblacion:  41234 },
    { nombre: 'Zona Bananera',           poblacion:  47234 },
    { nombre: 'Salamina',                poblacion:  14234 },
    { nombre: 'San Zenón',               poblacion:   9234 },
    { nombre: 'Tenerife',                poblacion:  16234 },
    { nombre: 'Cerro de San Antonio',    poblacion:  10234 },
    { nombre: 'El Retén',                poblacion:  17234 },
    { nombre: 'Pedraza',                 poblacion:  11234 },
    { nombre: 'Remolino',                poblacion:  11234 },
    { nombre: 'Sabanas de San Ángel',    poblacion:  12234 },
    { nombre: 'Santa Bárbara de Pinto',  poblacion:  13234 },
    { nombre: 'Sitionuevo',              poblacion:  19234 },
    { nombre: 'Guamal',                  poblacion:  21234 },
    { nombre: 'Algarrobo',               poblacion:  13234 },
    { nombre: 'Ariguaní',                poblacion:  30234 },
    { nombre: 'Chivolo',                 poblacion:  15234 },
    { nombre: 'Concordia',               poblacion:   9234 },
    { nombre: 'El Piñón',                poblacion:  16234 },
    { nombre: 'Nueva Granada',           poblacion:  16234 },
    { nombre: 'Pijiño del Carmen',       poblacion:   9234 },
    { nombre: 'Pueblo Viejo',            poblacion:  24234 },
    { nombre: 'San Sebastián de Buenavista', poblacion: 13234 },
    { nombre: 'Zapayán',                 poblacion:   9234 },
    { nombre: 'Sitio Nuevo',             poblacion:  19234 },
  ],

  // ── 54 · Norte de Santander ───────────────────────────────────────────
  '54': [
    { nombre: 'Cúcuta',                  poblacion: 726002 },
    { nombre: 'Ocaña',                   poblacion:  99234 },
    { nombre: 'Pamplona',                poblacion:  59234 },
    { nombre: 'Villa del Rosario',       poblacion: 106234 },
    { nombre: 'Los Patios',              poblacion: 100234 },
    { nombre: 'El Zulia',                poblacion:  40234 },
    { nombre: 'Tibú',                    poblacion:  57234 },
    { nombre: 'Convención',              poblacion:  17234 },
    { nombre: 'Teorama',                 poblacion:  15234 },
    { nombre: 'San Calixto',             poblacion:  13234 },
    { nombre: 'Abrego',                  poblacion:  35234 },
    { nombre: 'El Carmen',               poblacion:  16234 },
    { nombre: 'La Playa',                poblacion:   7234 },
    { nombre: 'Salazar',                 poblacion:  13234 },
    { nombre: 'Sardinata',               poblacion:  24234 },
    { nombre: 'Puerto Santander',        poblacion:  16234 },
    { nombre: 'Hacarí',                  poblacion:   9234 },
    { nombre: 'Chinácota',               poblacion:  14234 },
    { nombre: 'Cáchira',                 poblacion:   9234 },
    { nombre: 'Chitagá',                 poblacion:  10234 },
    { nombre: 'Cucutilla',               poblacion:   7234 },
    { nombre: 'Durania',                 poblacion:   6234 },
    { nombre: 'El Tarra',                poblacion:  14234 },
    { nombre: 'Gramalote',               poblacion:   7234 },
    { nombre: 'Herrán',                  poblacion:   5234 },
    { nombre: 'La Esperanza',            poblacion:  11234 },
    { nombre: 'Labateca',                poblacion:   6234 },
    { nombre: 'Lourdes',                 poblacion:   5234 },
    { nombre: 'Mutiscua',                poblacion:   5234 },
    { nombre: 'Ragonvalia',              poblacion:   8234 },
    { nombre: 'San Cayetano',            poblacion:   8234 },
    { nombre: 'Santiago',                poblacion:   7234 },
    { nombre: 'Silos',                   poblacion:   5234 },
    { nombre: 'Tolú Viejo',              poblacion:   7234 },
    { nombre: 'Toledo',                  poblacion:  17234 },
    { nombre: 'Villa Caro',              poblacion:   5234 },
    { nombre: 'Bochalema',               poblacion:   8234 },
    { nombre: 'Bucarasica',              poblacion:   7234 },
    { nombre: 'Cácota',                  poblacion:   3234 },
    { nombre: 'Arboledas',               poblacion:  10234 },
  ],

  // ── 68 · Santander ────────────────────────────────────────────────────
  '68': [
    { nombre: 'Bucaramanga',             poblacion: 581130 },
    { nombre: 'Floridablanca',           poblacion: 264312 },
    { nombre: 'Girón',                   poblacion: 207829 },
    { nombre: 'Piedecuesta',             poblacion: 157234 },
    { nombre: 'Barrancabermeja',         poblacion: 191234 },
    { nombre: 'San Gil',                 poblacion:  47234 },
    { nombre: 'Vélez',                   poblacion:  21234 },
    { nombre: 'Málaga',                  poblacion:  18234 },
    { nombre: 'Socorro',                 poblacion:  32234 },
    { nombre: 'Lebrija',                 poblacion:  45234 },
    { nombre: 'Curití',                  poblacion:  12234 },
    { nombre: 'Charalá',                 poblacion:  13234 },
    { nombre: 'Barbosa',                 poblacion:  29234 },
    { nombre: 'Aratoca',                 poblacion:   7234 },
    { nombre: 'Barichara',               poblacion:   8234 },
    { nombre: 'Capitanejo',              poblacion:   6234 },
    { nombre: 'Carcasí',                 poblacion:   5234 },
    { nombre: 'Cepitá',                  poblacion:   4234 },
    { nombre: 'Cerrito',                 poblacion:   7234 },
    { nombre: 'Chimá',                   poblacion:   4234 },
    { nombre: 'Chima',                   poblacion:   4234 },
    { nombre: 'Chipata',                 poblacion:   5234 },
    { nombre: 'Cimitarra',               poblacion:  31234 },
    { nombre: 'Confines',                poblacion:   4234 },
    { nombre: 'Contratación',            poblacion:   6234 },
    { nombre: 'Coromoro',                poblacion:   8234 },
    { nombre: 'El Carmen de Chucurí',    poblacion:  19234 },
    { nombre: 'El Guacamayo',            poblacion:   3234 },
    { nombre: 'El Peñón',                poblacion:   6234 },
    { nombre: 'El Playón',               poblacion:  15234 },
    { nombre: 'Encino',                  poblacion:   4234 },
    { nombre: 'Enciso',                  poblacion:   4234 },
    { nombre: 'Florián',                 poblacion:  11234 },
    { nombre: 'Gambita',                 poblacion:   6234 },
    { nombre: 'Guaca',                   poblacion:   9234 },
    { nombre: 'Guadalupe',               poblacion:  12234 },
    { nombre: 'Guapotá',                 poblacion:   4234 },
    { nombre: 'Guavatá',                 poblacion:   6234 },
    { nombre: 'Güepsa',                  poblacion:   6234 },
    { nombre: 'Hato',                    poblacion:   4234 },
    { nombre: 'Jesús María',             poblacion:   6234 },
    { nombre: 'La Belleza',              poblacion:  10234 },
    { nombre: 'La Paz',                  poblacion:   6234 },
    { nombre: 'Landázuri',               poblacion:  19234 },
    { nombre: 'Los Santos',              poblacion:   8234 },
    { nombre: 'Macaravita',              poblacion:   3234 },
    { nombre: 'Matanza',                 poblacion:   8234 },
    { nombre: 'Mogotes',                 poblacion:  13234 },
    { nombre: 'Molagavita',              poblacion:   5234 },
    { nombre: 'Ocamonte',                poblacion:   5234 },
    { nombre: 'Oiba',                    poblacion:  11234 },
    { nombre: 'Onzaga',                  poblacion:   6234 },
    { nombre: 'Palmar',                  poblacion:   5234 },
    { nombre: 'Palmas del Socorro',      poblacion:   4234 },
    { nombre: 'Páramo',                  poblacion:   5234 },
    { nombre: 'Pinchote',                poblacion:   5234 },
    { nombre: 'Puerto Parra',            poblacion:  10234 },
    { nombre: 'Puerto Wilches',          poblacion:  28234 },
    { nombre: 'Rionegro',                poblacion:  29234 },
    { nombre: 'Sabana de Torres',        poblacion:  21234 },
    { nombre: 'San Andrés',              poblacion:   9234 },
    { nombre: 'San Benito',              poblacion:   5234 },
    { nombre: 'San José de Miranda',     poblacion:   7234 },
    { nombre: 'San Miguel',              poblacion:   5234 },
    { nombre: 'San Vicente de Chucurí',  poblacion:  35234 },
    { nombre: 'Santa Bárbara',           poblacion:   8234 },
    { nombre: 'Santa Helena del Opón',   poblacion:   7234 },
    { nombre: 'Simacota',                poblacion:  10234 },
    { nombre: 'Suaita',                  poblacion:  10234 },
    { nombre: 'Sucre',                   poblacion:  10234 },
    { nombre: 'Suratá',                  poblacion:   5234 },
    { nombre: 'Tona',                    poblacion:   6234 },
    { nombre: 'Valle de San José',       poblacion:   8234 },
    { nombre: 'Vélez',                   poblacion:  21234 },
    { nombre: 'Vetas',                   poblacion:   3234 },
    { nombre: 'Villanueva',              poblacion:  13234 },
    { nombre: 'Zapatoca',                poblacion:  10234 },
  ],

  // ── 05 · Antioquia ────────────────────────────────────────────────────
  '05': [
    { nombre: 'Medellín',                poblacion:2700000 },
    { nombre: 'Bello',                   poblacion: 520234 },
    { nombre: 'Itagüí',                  poblacion: 272234 },
    { nombre: 'Envigado',                poblacion: 235234 },
    { nombre: 'Apartadó',                poblacion: 185234 },
    { nombre: 'Turbo',                   poblacion: 162234 },
    { nombre: 'Caucasia',                poblacion: 105234 },
    { nombre: 'Rionegro',                poblacion: 120234 },
    { nombre: 'La Ceja',                 poblacion:  62234 },
    { nombre: 'Sabaneta',                poblacion:  65234 },
    { nombre: 'Marinilla',               poblacion:  50234 },
    { nombre: 'El Carmen de Viboral',    poblacion:  51234 },
    { nombre: 'Yarumal',                 poblacion:  43234 },
    { nombre: 'Santa Rosa de Osos',      poblacion:  38234 },
    { nombre: 'Andes',                   poblacion:  42234 },
    { nombre: 'Jardín',                  poblacion:  15234 },
    { nombre: 'Ciudad Bolívar',          poblacion:  28234 },
    { nombre: 'Fredonia',                poblacion:  23234 },
    { nombre: 'Abejorral',               poblacion:  18234 },
    { nombre: 'Sonsón',                  poblacion:  28234 },
    { nombre: 'Guarne',                  poblacion:  46234 },
    { nombre: 'San Pedro de los Milagros', poblacion: 28234 },
    { nombre: 'Barbosa',                 poblacion:  50234 },
    { nombre: 'Copacabana',              poblacion:  70234 },
    { nombre: 'La Estrella',             poblacion:  63234 },
    { nombre: 'Caldas',                  poblacion:  78234 },
    { nombre: 'Girardota',               poblacion:  52234 },
    { nombre: 'Chigorodó',               poblacion:  67234 },
    { nombre: 'Carepa',                  poblacion:  40234 },
    { nombre: 'Mutatá',                  poblacion:  16234 },
    { nombre: 'Necoclí',                 poblacion:  38234 },
    { nombre: 'San Juan de Urabá',       poblacion:  22234 },
    { nombre: 'Arboletes',               poblacion:  37234 },
    { nombre: 'San Pedro de Urabá',      poblacion:  23234 },
    { nombre: 'Tarazá',                  poblacion:  34234 },
    { nombre: 'Cáceres',                 poblacion:  30234 },
    { nombre: 'Zaragoza',                poblacion:  24234 },
    { nombre: 'El Bagre',                poblacion:  35234 },
    { nombre: 'Nechí',                   poblacion:  20234 },
    { nombre: 'Segovia',                 poblacion:  37234 },
    { nombre: 'Remedios',                poblacion:  22234 },
    { nombre: 'Yolombó',                 poblacion:  21234 },
    { nombre: 'Yondó',                   poblacion:  20234 },
    { nombre: 'Puerto Berrío',           poblacion:  39234 },
    { nombre: 'Puerto Nare',             poblacion:  16234 },
    { nombre: 'Puerto Triunfo',          poblacion:  16234 },
    { nombre: 'Caracolí',                poblacion:   6234 },
    { nombre: 'San Carlos',              poblacion:  16234 },
    { nombre: 'San Rafael',              poblacion:  12234 },
    { nombre: 'Cocorná',                 poblacion:  17234 },
    { nombre: 'Granada',                 poblacion:  10234 },
    { nombre: 'San Francisco',           poblacion:   7234 },
    { nombre: 'San Luis',                poblacion:  13234 },
    { nombre: 'Alejandría',              poblacion:   5234 },
    { nombre: 'Concepción',              poblacion:   5234 },
    { nombre: 'El Santuario',            poblacion:  25234 },
    { nombre: 'Peñol',                   poblacion:  17234 },
    { nombre: 'Retiro',                  poblacion:  17234 },
    { nombre: 'San Vicente',             poblacion:  22234 },
    { nombre: 'Angostura',               poblacion:  11234 },
    { nombre: 'Campamento',              poblacion:   8234 },
    { nombre: 'Carolina',                poblacion:   5234 },
    { nombre: 'Don Matías',              poblacion:  17234 },
    { nombre: 'Entrerríos',              poblacion:   9234 },
    { nombre: 'Gómez Plata',             poblacion:  11234 },
    { nombre: 'Ituango',                 poblacion:  23234 },
    { nombre: 'San Andrés',              poblacion:   7234 },
    { nombre: 'San José de la Montaña',  poblacion:   5234 },
    { nombre: 'Toledo',                  poblacion:   7234 },
    { nombre: 'Valdivia',                poblacion:  16234 },
    { nombre: 'Liborina',                poblacion:   8234 },
    { nombre: 'Olaya',                   poblacion:   4234 },
    { nombre: 'Peque',                   poblacion:   8234 },
    { nombre: 'Sabanalarga',             poblacion:   8234 },
    { nombre: 'San Jerónimo',            poblacion:  12234 },
    { nombre: 'Sopetrán',                poblacion:  17234 },
    { nombre: 'Armenia',                 poblacion:   5234 },
    { nombre: 'Belmira',                 poblacion:   6234 },
    { nombre: 'Briceño',                 poblacion:   8234 },
    { nombre: 'Buriticá',                poblacion:   9234 },
    { nombre: 'Caicedo',                 poblacion:   7234 },
    { nombre: 'Dabeiba',                 poblacion:  20234 },
    { nombre: 'Frontino',                poblacion:  16234 },
    { nombre: 'Giraldo',                 poblacion:   4234 },
    { nombre: 'Heliconia',               poblacion:   8234 },
    { nombre: 'Hispania',                poblacion:   6234 },
    { nombre: 'Montebello',              poblacion:   8234 },
    { nombre: 'Pueblorrico',             poblacion:   8234 },
    { nombre: 'Santa Bárbara',           poblacion:  19234 },
    { nombre: 'Salgar',                  poblacion:  18234 },
    { nombre: 'Támesis',                 poblacion:  13234 },
    { nombre: 'Tarso',                   poblacion:   7234 },
    { nombre: 'Titiribí',                poblacion:  13234 },
    { nombre: 'Urrao',                   poblacion:  36234 },
    { nombre: 'Valparaíso',              poblacion:   8234 },
    { nombre: 'Venecia',                 poblacion:  10234 },
    { nombre: 'Anzá',                    poblacion:   8234 },
    { nombre: 'Ebéjico',                 poblacion:  11234 },
    { nombre: 'La Pintada',              poblacion:   8234 },
    { nombre: 'Montebello',              poblacion:   8234 },
    { nombre: 'Amagá',                   poblacion:  29234 },
    { nombre: 'Angelópolis',             poblacion:   8234 },
    { nombre: 'Concordia',               poblacion:  21234 },
    { nombre: 'Betulia',                 poblacion:  14234 },
    { nombre: 'Caramanta',               poblacion:   5234 },
    { nombre: 'La Pintada',              poblacion:   8234 },
  ],

  // ── 23 · Córdoba ──────────────────────────────────────────────────────
  '23': [
    { nombre: 'Montería',                poblacion: 434965 },
    { nombre: 'Montelíbano',             poblacion:  78234 },
    { nombre: 'Lorica',                  poblacion:  91234 },
    { nombre: 'Cereté',                  poblacion:  81234 },
    { nombre: 'Sahagún',                 poblacion:  82234 },
    { nombre: 'Tierralta',               poblacion:  79234 },
    { nombre: 'Planeta Rica',            poblacion:  69234 },
    { nombre: 'Ayapel',                  poblacion:  46234 },
    { nombre: 'Ciénaga de Oro',          poblacion:  47234 },
    { nombre: 'La Apartada',             poblacion:  12234 },
    { nombre: 'Moñitos',                 poblacion:  22234 },
    { nombre: 'Puerto Escondido',        poblacion:  19234 },
    { nombre: 'San Bernardo del Viento', poblacion:  26234 },
    { nombre: 'Chinú',                   poblacion:  35234 },
    { nombre: 'San Andrés de Sotavento', poblacion:  45234 },
    { nombre: 'San Antero',              poblacion:  22234 },
    { nombre: 'San Carlos',              poblacion:  19234 },
    { nombre: 'San Pelayo',              poblacion:  27234 },
    { nombre: 'Buenavista',              poblacion:  19234 },
    { nombre: 'Cotorra',                 poblacion:  15234 },
    { nombre: 'Momil',                   poblacion:  14234 },
    { nombre: 'Purísima',                poblacion:  15234 },
    { nombre: 'Tuchín',                  poblacion:  28234 },
    { nombre: 'Valencia',                poblacion:  28234 },
    { nombre: 'Pueblo Nuevo',            poblacion:  31234 },
    { nombre: 'Canalete',                poblacion:  19234 },
    { nombre: 'Los Córdobas',            poblacion:  14234 },
    { nombre: 'Chima',                   poblacion:   9234 },
    { nombre: 'Chimá',                   poblacion:   9234 },
    { nombre: 'Iris',                    poblacion:   3234 },
  ],

  // ── 27 · Chocó ────────────────────────────────────────────────────────
  '27': [
    { nombre: 'Quibdó',                  poblacion: 115234 },
    { nombre: 'Istmina',                 poblacion:  28234 },
    { nombre: 'Tadó',                    poblacion:  19234 },
    { nombre: 'Riosucio',                poblacion:  26234 },
    { nombre: 'Acandí',                  poblacion:  10234 },
    { nombre: 'Bahía Solano',            poblacion:   9234 },
    { nombre: 'Bojayá',                  poblacion:  11234 },
    { nombre: 'Nuquí',                   poblacion:   7234 },
    { nombre: 'Sipí',                    poblacion:   4234 },
    { nombre: 'Unguía',                  poblacion:  13234 },
    { nombre: 'El Litoral del San Juan', poblacion:   9234 },
    { nombre: 'Juradó',                  poblacion:   4234 },
    { nombre: 'Lloró',                   poblacion:   9234 },
    { nombre: 'Medio Atrato',            poblacion:  13234 },
    { nombre: 'Medio Baudó',             poblacion:  12234 },
    { nombre: 'Novita',                  poblacion:   7234 },
    { nombre: 'Río Iro',                 poblacion:   6234 },
    { nombre: 'Río Quito',               poblacion:   9234 },
    { nombre: 'San José del Palmar',     poblacion:   6234 },
    { nombre: 'Cértegui',                poblacion:   7234 },
    { nombre: 'Condoto',                 poblacion:  16234 },
    { nombre: 'El Cantón del San Pablo', poblacion:   8234 },
    { nombre: 'El Carmen de Atrato',     poblacion:   9234 },
    { nombre: 'La Sierra',               poblacion:   5234 },
    { nombre: 'La Virginia',             poblacion:   4234 },
    { nombre: 'Medio San Juan',          poblacion:  12234 },
    { nombre: 'Nóvita',                  poblacion:   7234 },
    { nombre: 'Bagadó',                  poblacion:   8234 },
    { nombre: 'Carmen del Darién',       poblacion:   7234 },
    { nombre: 'Bajo Baudó',              poblacion:  14234 },
  ],

  // ── 70 · Sucre ────────────────────────────────────────────────────────
  '70': [
    { nombre: 'Sincelejo',               poblacion: 278234 },
    { nombre: 'Corozal',                 poblacion:  61234 },
    { nombre: 'Sampués',                 poblacion:  38234 },
    { nombre: 'San Marcos',              poblacion:  56234 },
    { nombre: 'San Onofre',              poblacion:  42234 },
    { nombre: 'La Unión',                poblacion:  13234 },
    { nombre: 'Tolú',                    poblacion:  28234 },
    { nombre: 'Morroa',                  poblacion:  14234 },
    { nombre: 'Coveñas',                 poblacion:  13234 },
    { nombre: 'Palmito',                 poblacion:  16234 },
    { nombre: 'Sincé',                   poblacion:  22234 },
    { nombre: 'San Luis de Sincé',       poblacion:  22234 },
    { nombre: 'San Pedro',               poblacion:  14234 },
    { nombre: 'Buenavista',              poblacion:  10234 },
    { nombre: 'Chalán',                  poblacion:   5234 },
    { nombre: 'Coloso',                  poblacion:   8234 },
    { nombre: 'Caimito',                 poblacion:  11234 },
    { nombre: 'El Roble',                poblacion:   8234 },
    { nombre: 'Galeras',                 poblacion:  16234 },
    { nombre: 'Guaranda',                poblacion:  11234 },
    { nombre: 'La Apartada',             poblacion:   8234 },
    { nombre: 'Los Palmitos',            poblacion:  21234 },
    { nombre: 'Majagual',                poblacion:  23234 },
    { nombre: 'Ovejas',                  poblacion:  17234 },
    { nombre: 'Sucre',                   poblacion:  17234 },
    { nombre: 'Tolú Viejo',              poblacion:  18234 },
  ],

  // ── 17 · Caldas ───────────────────────────────────────────────────────
  '17': [
    { nombre: 'Manizales',               poblacion: 403046 },
    { nombre: 'Villamaría',              poblacion:  56234 },
    { nombre: 'La Dorada',               poblacion:  77234 },
    { nombre: 'Riosucio',                poblacion:  59234 },
    { nombre: 'Chinchiná',               poblacion:  51234 },
    { nombre: 'Neira',                   poblacion:  29234 },
    { nombre: 'Supía',                   poblacion:  24234 },
    { nombre: 'Manzanares',              poblacion:  23234 },
    { nombre: 'Salamina',                poblacion:  19234 },
    { nombre: 'Aguadas',                 poblacion:  20234 },
    { nombre: 'Anserma',                 poblacion:  28234 },
    { nombre: 'Aranzazu',                poblacion:  11234 },
    { nombre: 'Belalcázar',              poblacion:  10234 },
    { nombre: 'Filadelfia',              poblacion:   9234 },
    { nombre: 'La Merced',               poblacion:   6234 },
    { nombre: 'Marulanda',               poblacion:   5234 },
    { nombre: 'Pácora',                  poblacion:  11234 },
    { nombre: 'Palestina',               poblacion:  15234 },
    { nombre: 'Pensilvania',             poblacion:  19234 },
    { nombre: 'Risaralda',               poblacion:   9234 },
    { nombre: 'San José',                poblacion:   5234 },
    { nombre: 'Samaná',                  poblacion:  19234 },
    { nombre: 'Viterbo',                 poblacion:  13234 },
    { nombre: 'Victoria',                poblacion:   9234 },
    { nombre: 'Marquetalia',             poblacion:  13234 },
    { nombre: 'Norcasia',                poblacion:   7234 },
    { nombre: 'Pácora',                  poblacion:  11234 },
  ],

  // ── 18 · Caquetá ──────────────────────────────────────────────────────
  '18': [
    { nombre: 'Florencia',               poblacion: 169234 },
    { nombre: 'San Vicente del Caguán',  poblacion:  65234 },
    { nombre: 'El Doncello',             poblacion:  22234 },
    { nombre: 'El Paujil',               poblacion:  20234 },
    { nombre: 'Belén de los Andaquíes',  poblacion:  12234 },
    { nombre: 'La Montañita',            poblacion:  21234 },
    { nombre: 'Morelia',                 poblacion:   7234 },
    { nombre: 'Puerto Rico',             poblacion:  18234 },
    { nombre: 'Solano',                  poblacion:  13234 },
    { nombre: 'Solita',                  poblacion:   7234 },
    { nombre: 'Valparaíso',              poblacion:   8234 },
    { nombre: 'Albania',                 poblacion:   6234 },
    { nombre: 'Cartagena del Chairá',    poblacion:  28234 },
    { nombre: 'Curillo',                 poblacion:  11234 },
    { nombre: 'Milán',                   poblacion:  11234 },
    { nombre: 'Paujil',                  poblacion:  20234 },
  ],

  // ── 19 · Cauca ────────────────────────────────────────────────────────
  '19': [
    { nombre: 'Popayán',                 poblacion: 330234 },
    { nombre: 'Santander de Quilichao',  poblacion:  96234 },
    { nombre: 'Puerto Tejada',           poblacion:  46234 },
    { nombre: 'Corinto',                 poblacion:  32234 },
    { nombre: 'Miranda',                 poblacion:  32234 },
    { nombre: 'El Tambo',                poblacion:  39234 },
    { nombre: 'Patía',                   poblacion:  31234 },
    { nombre: 'Guapi',                   poblacion:  31234 },
    { nombre: 'Caloto',                  poblacion:  26234 },
    { nombre: 'Timbío',                  poblacion:  26234 },
    { nombre: 'Padilla',                 poblacion:  16234 },
    { nombre: 'Buenos Aires',            poblacion:  29234 },
    { nombre: 'Cajibío',                 poblacion:  32234 },
    { nombre: 'Caldono',                 poblacion:  22234 },
    { nombre: 'Florencia',               poblacion:   7234 },
    { nombre: 'Inzá',                    poblacion:  16234 },
    { nombre: 'Jambaló',                 poblacion:  12234 },
    { nombre: 'La Sierra',               poblacion:   8234 },
    { nombre: 'La Vega',                 poblacion:  21234 },
    { nombre: 'Mercaderes',              poblacion:  14234 },
    { nombre: 'Morales',                 poblacion:  18234 },
    { nombre: 'Páez',                    poblacion:  20234 },
    { nombre: 'Piamonte',                poblacion:   8234 },
    { nombre: 'Piendamó',                poblacion:  28234 },
    { nombre: 'Rosas',                   poblacion:  10234 },
    { nombre: 'San Sebastián',           poblacion:   7234 },
    { nombre: 'Santa Rosa',              poblacion:  10234 },
    { nombre: 'Silvia',                  poblacion:  30234 },
    { nombre: 'Sotara',                  poblacion:  12234 },
    { nombre: 'Suárez',                  poblacion:  22234 },
    { nombre: 'Sucre',                   poblacion:  12234 },
    { nombre: 'Timbiquí',                poblacion:  19234 },
    { nombre: 'Toribío',                 poblacion:  22234 },
    { nombre: 'Totoró',                  poblacion:  11234 },
    { nombre: 'Villa Rica',              poblacion:  14234 },
    { nombre: 'Almaguer',                poblacion:  13234 },
    { nombre: 'Argelia',                 poblacion:  20234 },
    { nombre: 'Balboa',                  poblacion:  12234 },
    { nombre: 'Bolívar',                 poblacion:  23234 },
    { nombre: 'Coconuco',                poblacion:   7234 },
    { nombre: 'Florencia',               poblacion:   7234 },
    { nombre: 'López de Micay',          poblacion:  17234 },
    { nombre: 'Olaya Herrera',           poblacion:  17234 },
  ],

  // ── 41 · Huila ────────────────────────────────────────────────────────
  '41': [
    { nombre: 'Neiva',                   poblacion: 344117 },
    { nombre: 'Pitalito',                poblacion: 116234 },
    { nombre: 'Garzón',                  poblacion:  64234 },
    { nombre: 'La Plata',                poblacion:  57234 },
    { nombre: 'Campoalegre',             poblacion:  36234 },
    { nombre: 'Palermo',                 poblacion:  28234 },
    { nombre: 'Rivera',                  poblacion:  22234 },
    { nombre: 'Gigante',                 poblacion:  26234 },
    { nombre: 'San Agustín',             poblacion:  28234 },
    { nombre: 'Acevedo',                 poblacion:  22234 },
    { nombre: 'Aipe',                    poblacion:  19234 },
    { nombre: 'Algeciras',               poblacion:  18234 },
    { nombre: 'Altamira',                poblacion:   5234 },
    { nombre: 'Baraya',                  poblacion:  10234 },
    { nombre: 'Colombia',                poblacion:   9234 },
    { nombre: 'Elías',                   poblacion:   4234 },
    { nombre: 'Guadalupe',               poblacion:  13234 },
    { nombre: 'Hobo',                    poblacion:   7234 },
    { nombre: 'Íquira',                  poblacion:   8234 },
    { nombre: 'Isnos',                   poblacion:  19234 },
    { nombre: 'La Argentina',            poblacion:  11234 },
    { nombre: 'Nátaga',                  poblacion:   5234 },
    { nombre: 'Oporapa',                 poblacion:   9234 },
    { nombre: 'Paicol',                  poblacion:   6234 },
    { nombre: 'Palestina',               poblacion:   8234 },
    { nombre: 'Pital',                   poblacion:  10234 },
    { nombre: 'Saladoblanco',            poblacion:   9234 },
    { nombre: 'San Benito Abad',         poblacion:   4234 },
    { nombre: 'Santa María',             poblacion:  10234 },
    { nombre: 'Suaza',                   poblacion:  12234 },
    { nombre: 'Tarqui',                  poblacion:  16234 },
    { nombre: 'Tesalia',                 poblacion:   8234 },
    { nombre: 'Tello',                   poblacion:  12234 },
    { nombre: 'Teruel',                  poblacion:   8234 },
    { nombre: 'Timaná',                  poblacion:  14234 },
    { nombre: 'Villavieja',              poblacion:   8234 },
    { nombre: 'Yaguará',                 poblacion:   7234 },
  ],

  // ── 52 · Nariño ───────────────────────────────────────────────────────
  '52': [
    { nombre: 'Pasto',                   poblacion: 441234 },
    { nombre: 'Ipiales',                 poblacion: 116234 },
    { nombre: 'Tumaco',                  poblacion: 204234 },
    { nombre: 'Túquerres',               poblacion:  33234 },
    { nombre: 'La Unión',                poblacion:  30234 },
    { nombre: 'El Charco',               poblacion:  30234 },
    { nombre: 'Samaniego',               poblacion:  42234 },
    { nombre: 'Barbacoas',               poblacion:  34234 },
    { nombre: 'Cumbal',                  poblacion:  29234 },
    { nombre: 'Sandoná',                 poblacion:  18234 },
    { nombre: 'Guachucal',               poblacion:  15234 },
    { nombre: 'La Florida',              poblacion:  11234 },
    { nombre: 'Los Andes',               poblacion:  21234 },
    { nombre: 'Ricaurte',                poblacion:  28234 },
    { nombre: 'San Pablo',               poblacion:   9234 },
    { nombre: 'Buesaco',                 poblacion:  18234 },
    { nombre: 'Colón',                   poblacion:   9234 },
    { nombre: 'Consacá',                 poblacion:  10234 },
    { nombre: 'Contadero',               poblacion:   6234 },
    { nombre: 'Córdoba',                 poblacion:  11234 },
    { nombre: 'Cuaspud',                 poblacion:   8234 },
    { nombre: 'Cumbitara',               poblacion:  12234 },
    { nombre: 'Chachagüí',               poblacion:  10234 },
    { nombre: 'El Peñol',                poblacion:   7234 },
    { nombre: 'El Rosario',              poblacion:  11234 },
    { nombre: 'El Tablón de Gómez',      poblacion:  10234 },
    { nombre: 'Funes',                   poblacion:   6234 },
    { nombre: 'Guaitarilla',             poblacion:  14234 },
    { nombre: 'Gualmatán',               poblacion:   6234 },
    { nombre: 'Iles',                    poblacion:   6234 },
    { nombre: 'Imués',                   poblacion:   6234 },
    { nombre: 'La Llanada',              poblacion:   7234 },
    { nombre: 'La Tola',                 poblacion:   8234 },
    { nombre: 'Leiva',                   poblacion:  12234 },
    { nombre: 'Linares',                 poblacion:  13234 },
    { nombre: 'Magüí',                   poblacion:  18234 },
    { nombre: 'Mallama',                 poblacion:  12234 },
    { nombre: 'Mosquera',                poblacion:  13234 },
    { nombre: 'Nariño',                  poblacion:   9234 },
    { nombre: 'Olaya Herrera',           poblacion:  17234 },
    { nombre: 'Ospina',                  poblacion:   6234 },
    { nombre: 'Policarpa',               poblacion:  15234 },
    { nombre: 'Potosí',                  poblacion:  15234 },
    { nombre: 'Providencia',             poblacion:   5234 },
    { nombre: 'Puerres',                 poblacion:   8234 },
    { nombre: 'Pupiales',                poblacion:  14234 },
    { nombre: 'Sotomayor',               poblacion:  13234 },
    { nombre: 'Taminango',               poblacion:  18234 },
    { nombre: 'Tangua',                  poblacion:  10234 },
    { nombre: 'Francisco Pizarro',       poblacion:  10234 },
    { nombre: 'Roberto Payán',           poblacion:  15234 },
    { nombre: 'Santa Bárbara',           poblacion:  12234 },
    { nombre: 'Sapuyes',                 poblacion:   6234 },
    { nombre: 'Yacuanquer',              poblacion:   9234 },
    { nombre: 'Aldana',                  poblacion:   6234 },
    { nombre: 'Ancuyá',                  poblacion:   6234 },
    { nombre: 'Arboleda',                poblacion:  10234 },
    { nombre: 'Belén',                   poblacion:   7234 },
    { nombre: 'Cartago',                 poblacion:   8234 },
    { nombre: 'Chiles',                  poblacion:   5234 },
    { nombre: 'El Tambo',                poblacion:  26234 },
    { nombre: 'Génova',                  poblacion:   6234 },
    { nombre: 'Nariño',                  poblacion:   9234 },
  ],

  // ── 63 · Quindío ──────────────────────────────────────────────────────
  '63': [
    { nombre: 'Armenia',                 poblacion: 296234 },
    { nombre: 'Calarcá',                 poblacion:  80234 },
    { nombre: 'Montenegro',              poblacion:  43234 },
    { nombre: 'La Tebaida',              poblacion:  36234 },
    { nombre: 'Quimbaya',                poblacion:  37234 },
    { nombre: 'Circasia',                poblacion:  31234 },
    { nombre: 'Filandia',                poblacion:  13234 },
    { nombre: 'Buenavista',              poblacion:   7234 },
    { nombre: 'Córdoba',                 poblacion:   9234 },
    { nombre: 'Génova',                  poblacion:  10234 },
    { nombre: 'Pijao',                   poblacion:   7234 },
    { nombre: 'Salento',                 poblacion:   8234 },
  ],

  // ── 66 · Risaralda ────────────────────────────────────────────────────
  '66': [
    { nombre: 'Pereira',                 poblacion: 474234 },
    { nombre: 'Dosquebradas',            poblacion: 202234 },
    { nombre: 'Santa Rosa de Cabal',     poblacion:  78234 },
    { nombre: 'La Virginia',             poblacion:  34234 },
    { nombre: 'Quinchía',                poblacion:  30234 },
    { nombre: 'Belén de Umbría',         poblacion:  27234 },
    { nombre: 'Marsella',                poblacion:  23234 },
    { nombre: 'Santuario',               poblacion:  18234 },
    { nombre: 'Guática',                 poblacion:  14234 },
    { nombre: 'Mistrató',                poblacion:  12234 },
    { nombre: 'Pueblo Rico',             poblacion:  14234 },
    { nombre: 'La Celia',                poblacion:   9234 },
    { nombre: 'Apía',                    poblacion:  16234 },
    { nombre: 'Balboa',                  poblacion:   7234 },
  ],

  // ── 73 · Tolima ───────────────────────────────────────────────────────
  '73': [
    { nombre: 'Ibagué',                  poblacion: 559234 },
    { nombre: 'Espinal',                 poblacion:  83234 },
    { nombre: 'Melgar',                  poblacion:  34234 },
    { nombre: 'Honda',                   poblacion:  28234 },
    { nombre: 'Purificación',            poblacion:  28234 },
    { nombre: 'Líbano',                  poblacion:  42234 },
    { nombre: 'Fresno',                  poblacion:  29234 },
    { nombre: 'Mariquita',               poblacion:  36234 },
    { nombre: 'Chaparral',               poblacion:  47234 },
    { nombre: 'Guamo',                   poblacion:  29234 },
    { nombre: 'Flandes',                 poblacion:  24234 },
    { nombre: 'Villahermosa',            poblacion:  12234 },
    { nombre: 'Armero-Guayabal',         poblacion:  12234 },
    { nombre: 'Ambalema',                poblacion:   8234 },
    { nombre: 'Alvarado',                poblacion:   9234 },
    { nombre: 'Anzoátegui',              poblacion:  10234 },
    { nombre: 'Ataco',                   poblacion:  17234 },
    { nombre: 'Cajamarca',               poblacion:  19234 },
    { nombre: 'Carmen de Apicalá',       poblacion:   7234 },
    { nombre: 'Casabianca',              poblacion:   7234 },
    { nombre: 'Coello',                  poblacion:   8234 },
    { nombre: 'Coyaima',                 poblacion:  22234 },
    { nombre: 'Cunday',                  poblacion:   9234 },
    { nombre: 'Dolores',                 poblacion:   8234 },
    { nombre: 'Falan',                   poblacion:   8234 },
    { nombre: 'Herveo',                  poblacion:   8234 },
    { nombre: 'Icononzo',                poblacion:   8234 },
    { nombre: 'Lérida',                  poblacion:  18234 },
    { nombre: 'Murillo',                 poblacion:   4234 },
    { nombre: 'Natagaima',               poblacion:  19234 },
    { nombre: 'Ortega',                  poblacion:  31234 },
    { nombre: 'Palocabildo',             poblacion:   8234 },
    { nombre: 'Piedras',                 poblacion:   6234 },
    { nombre: 'Planadas',                poblacion:  21234 },
    { nombre: 'Prado',                   poblacion:   7234 },
    { nombre: 'Rioblanco',               poblacion:  22234 },
    { nombre: 'Roncesvalles',            poblacion:   5234 },
    { nombre: 'Rovira',                  poblacion:  18234 },
    { nombre: 'Saldaña',                 poblacion:  15234 },
    { nombre: 'San Antonio',             poblacion:   8234 },
    { nombre: 'San Luis',                poblacion:   9234 },
    { nombre: 'Santa Isabel',            poblacion:   5234 },
    { nombre: 'Suárez',                  poblacion:   7234 },
    { nombre: 'Valle de San Juan',       poblacion:   7234 },
    { nombre: 'Venadillo',               poblacion:  17234 },
    { nombre: 'Villahermosa',            poblacion:  12234 },
    { nombre: 'Villarrica',              poblacion:   6234 },
  ],

  // ── 76 · Valle del Cauca ──────────────────────────────────────────────
  '76': [
    { nombre: 'Cali',                    poblacion:2200000 },
    { nombre: 'Buenaventura',            poblacion: 415234 },
    { nombre: 'Palmira',                 poblacion: 308234 },
    { nombre: 'Buga',                    poblacion: 120234 },
    { nombre: 'Cartago',                 poblacion: 133234 },
    { nombre: 'Tuluá',                   poblacion: 216234 },
    { nombre: 'Yumbo',                   poblacion: 111234 },
    { nombre: 'Jamundí',                 poblacion: 111234 },
    { nombre: 'Candelaria',              poblacion:  80234 },
    { nombre: 'Caicedonia',              poblacion:  28234 },
    { nombre: 'Sevilla',                 poblacion:  46234 },
    { nombre: 'Roldanillo',              poblacion:  35234 },
    { nombre: 'El Cerrito',              poblacion:  34234 },
    { nombre: 'Ginebra',                 poblacion:  19234 },
    { nombre: 'Guacarí',                 poblacion:  25234 },
    { nombre: 'La Unión',                poblacion:  38234 },
    { nombre: 'La Victoria',             poblacion:  13234 },
    { nombre: 'Obando',                  poblacion:  14234 },
    { nombre: 'Restrepo',                poblacion:  15234 },
    { nombre: 'Riofrío',                 poblacion:  14234 },
    { nombre: 'San Pedro',               poblacion:  20234 },
    { nombre: 'Toro',                    poblacion:  15234 },
    { nombre: 'Trujillo',                poblacion:  20234 },
    { nombre: 'Ulloa',                   poblacion:   5234 },
    { nombre: 'Versalles',               poblacion:   8234 },
    { nombre: 'Vijes',                   poblacion:   8234 },
    { nombre: 'Yotoco',                  poblacion:  12234 },
    { nombre: 'Zarzal',                  poblacion:  41234 },
    { nombre: 'Alcalá',                  poblacion:  17234 },
    { nombre: 'Andalucía',               poblacion:  17234 },
    { nombre: 'Ansermanuevo',            poblacion:  16234 },
    { nombre: 'Argelia',                 poblacion:   9234 },
    { nombre: 'Bolívar',                 poblacion:  19234 },
    { nombre: 'Buenaventura',            poblacion: 415234 },
    { nombre: 'Bugalagrande',            poblacion:  19234 },
    { nombre: 'Calima',                  poblacion:  14234 },
    { nombre: 'Dagua',                   poblacion:  35234 },
    { nombre: 'El Águila',               poblacion:   9234 },
    { nombre: 'El Cairo',                poblacion:   8234 },
    { nombre: 'El Dovio',                poblacion:  10234 },
    { nombre: 'Florida',                 poblacion:  56234 },
    { nombre: 'Pradera',                 poblacion:  50234 },
    { nombre: 'El Darién',               poblacion:   9234 },
  ],

  // ── 86 · Putumayo ─────────────────────────────────────────────────────
  '86': [
    { nombre: 'Mocoa',                   poblacion:  44234 },
    { nombre: 'Puerto Asís',             poblacion:  62234 },
    { nombre: 'Orito',                   poblacion:  39234 },
    { nombre: 'La Hormiga',              poblacion:  29234 },
    { nombre: 'Sibundoy',                poblacion:  19234 },
    { nombre: 'Valle del Guamuez',       poblacion:  29234 },
    { nombre: 'San Miguel',              poblacion:  20234 },
    { nombre: 'Puerto Leguízamo',        poblacion:  18234 },
    { nombre: 'Puerto Guzmán',           poblacion:  17234 },
    { nombre: 'Colón',                   poblacion:   7234 },
    { nombre: 'Santiago',                poblacion:   6234 },
    { nombre: 'San Francisco',           poblacion:   6234 },
    { nombre: 'Villagarzón',             poblacion:  22234 },
  ],

  // ── 88 · San Andrés ───────────────────────────────────────────────────
  '88': [
    { nombre: 'San Andrés',              poblacion:  77234 },
    { nombre: 'Providencia',             poblacion:   5234 },
  ],
}
